# Setup
title: Three Month
description: 不會寫程式的AI套模仔。
url: https://threemonth03.github.io/not-pure-poole/
avatar: /profile.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: sankagetsu
  card: summary
logo: logo.png
social:
  name: ThreeMonth03
  links:
    - https://twitter.com/Thre3Month
    - https://github.com/ThreeMonth03
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
disqus: threemonth03

# Specify the author for blog posts
author:
  name: ThreeMonth03
  url: https://github.com/ThreeMonth03/
  email: mailto://austin20463@gmail.com
